<?php

class Web4pro_Linksgenerator_Block_Adminhtml_Linksgenerator extends Mage_Adminhtml_Block_Widget_Grid_Container {

    protected function _construct()
    {
        $this->_controller = 'adminhtml_linksgenerator';
        $this->_blockGroup = 'linksgenerator';
        $helper = Mage::helper('linksgenerator');

        $this->_headerText = $helper->__('Links Management');
        $this->_addButtonLabel = $helper->__('Add Link');

        parent::_construct(); // TODO: Change the autogenerated stub
    }
}

/*
class Web4pro_Linksgenerator_Block_Adminhtml_Linksgenerator extends Mage_Adminhtml_Block_Abstract
{

    public function _toHtml()
    {
        return '<h1>Linksgenerator Module: Admin section</h1>';
    }

}*/