<?php
class Web4pro_Linksgenerator_Model_Link extends Mage_Core_Model_Abstract {

    public function _construct()
    {
        parent::_construct();
        $this->_init('linksgenerator/link');
    }

    protected function _afterSave()
    {
        //TODO: save data into the bind table
        $this->getBindInstance()->saveLinksRelations($this);
        return parent::_afterSave(); // TODO: Change the autogenerated stub
    }
    //TODO: add method getBindInstance

    /**
     * @return Web4pro_Linksgenerator_Model_Bind
     */
    protected function getBindInstance()
    {
        return Mage::getModel('linksgenerator/bind');
    }
}